### ISSUE TITLE
About developing AutoTinderNavigation and AutoHiveNavigation?

### ISSUE THREAD

**Issue by lostkevin** [code2X/DspMods#13]
@jimmieclark3 Hello, do you have any plans to develop the auto navigation function to hive or tinder recently?

**Comment by jimmieclark3** [comment]
What's a tinder?  I did want the "to hive" functionality.  This plugin is designed to auto navigate to things you can target in your starmap.  Since hive is not targetable, that is where the struggle is.  It will need a UI to select the unselectable targets.

If enough people want this, I would gladly add it.

**Comment by lostkevin** [comment]
The tinder is a special enemy generated by hive which will become a new
hive in the target galaxy system. Since DSP V0.10.28.21308，It can be
selected by double clicks in the starmap，where the hive can also be
targeted like planet/star. The navigation to the tinder may be more
complicated because it use different API/variable to target/store the
relative location.

Finally，If you do not have any plans，I will try to add these functions. If
I have any problems in the development，I will contact through this issue.

jimmieclark3 ***@***.***> 于 2024年1月14日周日 上午3:13写道：

**Comment by jimmieclark3** [comment]
Either way man, if you want to suck down my changes, and move on that is fine by me.  I was just trying to fix a broken plugin at the time.

**Comment by jimmieclark3** [comment]
I'm not used to devs responding after a long time.  So if you wanted me to do a pull request and add to it at times, I can, no issues here.

**Comment by lostkevin** [comment]
I do not know how to upload the compiled mod to r2. Therefore I will make a
pull request on your fork if I make the new feature work.
jimmieclark3 ***@***.***> 于 2024年1月14日周日 下午12:59写道：

**Comment by jimmieclark3** [comment]
Sure, sounds good. I've been a c# coder for many years.  I will help.

**Comment by lostkevin** [comment]
Thanks. I write Python/C++ for years，but just a beginner of C#/Unity. I
will open a issue if I need some help.

jimmieclark3 ***@***.***> 于 2024年1月14日周日 下午1:07写道：

**Comment by jimmieclark3** [comment]
Sounds good
