### ISSUE TITLE
About auto stop feature

### ISSUE THREAD

**Issue by lostkevin** [code2X/DspMods#14]
@jimmieclark3 Because the lastDist in class SailMode_AutoNavigate is static, does this mean the auto stop feature will use two wrappers 
 in some cases when lastDist is small (after the most recent navigation) and the cdist is large (e.g., galaxy navigation)? 

```c#
        [HarmonyPatch(typeof(PlayerMove_Sail), "GameTick")]
        private class SailMode_AutoNavigate
        {
            private static VectorLF3 oTargetURot;
            private static double? lastDist;

            private static void Prefix(PlayerMove_Sail __instance)
            {
                if (!s_NavigateInstance.enable)
                    return;

                if (!__instance.player.sailing && !__instance.player.warping)
                    return;

                ++__instance.controller.input0.y;
                //oTargetURot = __instance.sailPoser.targetURot;
                oTargetURot = __instance.controller.fwdRayUDir;

                if (__instance.player.warping)
                {
                    var cdist = s_NavigateInstance.target.GetDistance(__instance.player);
                    if (lastDist != null)
                    {
                        if (lastDist < cdist)
                        {
                            ModDebug.Trace($"Dropping out of warp, passed target - ld:{lastDist} cd:{cdist}");
                            //We passed the target, drop out of warp, retarget
                            AutoStellarNavigation.Warp.TryLeaveWarp(__instance, false);
                        }
                    }
                    lastDist = cdist;
                }


                if (s_NavigateInstance.IsCurNavStar)
                    s_NavigateInstance.StarNavigation(__instance);
                else if (s_NavigateInstance.IsCurNavPlanet)
                    s_NavigateInstance.PlanetNavigation(__instance);
            }
```

**Comment by jimmieclark3** [comment]
I added this feature,  for when you crank warp up and you miss a planet.   It drops you out of warp.  You turn and it layman's again if needed.   I've seen it keep missing a planet until you run out of power, before this fix.

**Comment by jimmieclark3** [comment]
To use it elsewhere,  we should rework its location.  The way the classes are setup is bad coding for expansion. Want me to do some refactoring to make it easier?

**Comment by lostkevin** [comment]
I get the idea，but shouldn’t lastDist be initialized with double.MaxValue
before every navigation？

jimmieclark3 ***@***.***> 于 2024年1月16日周二 上午1:01写道：

**Comment by lostkevin** [comment]
> To use it elsewhere,  we should rework its location.  The way the classes are setup is bad coding for expansion. Want me to do some refactoring to make it easier?

Sure，I’ve done some refactorization on the codebase in my pull request，but it is still a bit messy.

**Comment by lostkevin** [comment]
> I get the idea，but shouldn’t lastDist be initialized with double.MaxValue before every navigation？

I add this feature by moving the lastDist outside and initialize the value when the key `K` is down in the PR. I hope it will work.

**Comment by jimmieclark3** [comment]
Uh, sure, that's a pretty good idea.  I thought we set distance when nav starts tho.  If not, we should set it with something.  Max value is probably better than the target dist, just in case your aiming the wrong way.
